### ISSUE TITLE
Support for svelte compiler 'cascade' option

### ISSUE THREAD

**Issue by cotlod** [sveltejs/svelte-loader#117]
You cannot currently toggle on or off the cascade option that was added to svelte 2

https://github.com/sveltejs/svelte/pull/607

Cheers!

**Comment by Conduitry** [comment]
`cascade` was added in [v1.22.0](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#1220), and was _removed_ in [v2.0.0](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#200). It was added so that switching to component-scoped styles would be opt-in and wouldn't be a breaking change - and as of v2 scoped styles are all that's available. There's nothing here to configure post-v2.

**Comment by cotlod** [comment]
Thanks for the info!
