### ISSUE TITLE
Remove options.externalDependencies?

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-loader#77]
Looking at this properly for the first time, and I'm not sure I understand how it's used: https://github.com/sveltejs/svelte-loader#external-dependencies

Is it something that can be removed now that we have #75?

cc @rob-balfre

**Comment by rob-balfre** [comment]
@Rich-Harris we currently use this in our webpack build to watch files used in preprocessing which aren't directly imported into the codebase.  At first glance I think #75 is a seperate issue.

For example when preprocessing styles with postcss-load-config we supply svelte-loader with externalDependencies and any changes made to those deps will automatically update the build, otherwise it becomes very laborious manually restarting webpack.

**Comment by Rich-Harris** [comment]
Interesting. Shouldn't the preprocessor still be responsible for declaring those dependencies? Or is that not possible?

**Comment by rob-balfre** [comment]
If there is a way to get CSS variables working via an @import in a Svelte <style> tag I don't mind whether its a preprocessor or external dependency.  The only way we've managed to get it working currently is via svelte-loader -> postcss -> postcss-custom-properties -> external-dependencies.  This is all to support IE11 so our CSS variables work 😥
