### ISSUE TITLE
add hot support

### ISSUE THREAD

**Issue by tehOPEologist** [sveltejs/svelte-loader#8]
looks like right now when running webpack-dev-server with hot enabled and modifying a component in a svelte app the module that tries to hot reload is labelled as unacceptable and logs out that you should do a full reload to see the changes.

**Comment by nikku** [comment]
That may be the case. To my knowledge, hot reloading does not work out of the box anyway but requires framework / application support (e.g. stateless views).

I welcome any pointers how tackle this issue.

**Comment by tehOPEologist** [comment]
i think the problem right now is that svelte doesn't keep a record of the modules used, since all that's output in the bundle is the compiled code for rendering.  without a record, this won't work...  seems @Rich-Harris would need to add in record collection into svelte for this to work.  i wonder if that's something we could flag in the loader and would only run if the option was enabled so the records wouldn't get sent in a prod build?  that might work...

**Comment by tehOPEologist** [comment]
i'm assuming this from reading this: https://webpack.github.io/docs/hot-module-replacement-with-webpack.html#what-is-needed-to-use-it

**Comment by Rich-Harris** [comment]
> svelte doesn't keep a record of the modules used

Isn't that Webpack's job? Not quite sure how it works.

@guzart you're probably the most knowledgable person on this topic at the moment – were you able to get hot reloading working with Svelte?

I don't see any fundamental reason why it should be impossible, though I'm not coming from a position of authority. Isn't it just a case of doing this, for each instance of a component whose source code has changed?

1. grab the existing state with `data = component.get()`
2. tear down the component with `component.teardown()`
3. instantiate a new component in the same place

We'd need some way to track instances, and a way to find their location in the DOM. (Unless the responsibility for swapping out the component sits with its consumers, rather than the component itself?)

**Comment by tehOPEologist** [comment]
yeah this is about as far as i go as far as assistance unfortunately lol, but i wanted to open this conversation to see if it's possible and ifso, how.  thanks a bunch all!

**Comment by guzart** [comment]
I was able to get very basic HMR by adding the following code after each instance creation.

```js
// somewhere global
global.hotify = function (instance, options, Component) {
  var data = instance.get();
  instance.teardown();
  return new Component(Object.assign({}, options, { data: data }));
};

// injected into the App.svelte that requires Profile.svelte
var profile = new template.components.Profile({ target: target, parent: component, data: profile_initialData });

// injected by babel, or whatever plugin
if (module.hot) {
  (function (opts) {
    module.hot.accept('./Profile.svelte', () => {
      profile = global.hotify(profile, opts, require('./Profile.svelte'));
    });
  })({ target: target, parent: component, data: profile_initialData });
}
```

It works for a simple one instance component, the problem is when dealing with blocks. 
One challenge is to re-create the instances inside an `renderEachBlock`.

**Comment by ekhaled** [comment]
[svelte-hot-loader](https://github.com/ekhaled/svelte-hot-loader) has just reached stable 1.0

Give it a try :smile:
Also, PRs always welcome
